### ISSUE TITLE
Rework try.purescript.org

### ISSUE THREAD

**Issue by i-am-the-slime** [working-group-purescript-es/trypurescript#1]
Originally written by @natefaubion

Additionally, there's stuff like try.purescript.org that needs to be reworked for es modules, and may just require dropping old browser support (which is fine by me).

**Comment by natefaubion** [comment]
I think using a 3rd party ESM loader shim like SystemJS is probably the most straightforward way to resolve this.
https://github.com/systemjs/systemjs

Using import maps would let us retain support for things like React.

**Comment by thomashoneyman** [comment]
I've written up two issues capturing at least some of what we would have to do -- feel free to weigh in on those!

[Proposal: Load foreign code with SystemJS and import maps](https://github.com/purescript/trypurescript/issues/263)
[Proposal: Introduce esbuild for Try PureScript](https://github.com/purescript/trypurescript/issues/264)
